### ISSUE TITLE
Getting a python error. 

### ISSUE THREAD

**Issue by SyRaza** [jayanam/jremesh-tools#7]
I have no idea what this means but this is the error I'm getting. I'm on blender 3.3.1

```
Python: Traceback (most recent call last):
  File "C:\Users\Sy\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\jremesh-tools-main\jrt_remesh_op.py", line 74, in execute
    bpy.ops.export_scene.obj(filepath=orig,
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.export_scene.obj" error, could not be found

```

**Comment by bekmeh** [comment]
I had the same error, and resolved it by enabling the plugin called "Import-Export: Wavefront OBJ format (legacy)"

**Comment by jakub-bak** [comment]
> I had the same error, and resolved it by enabling the plugin called "Import-Export: Wavefront OBJ format (legacy)"

That resolves the issue indeed, worth mentioning in the DOCS as some users disabled that legacy importer for startup time savings.

**Comment by dfsadfsfsa** [comment]
Ive just had the same error using Blender 4.0.  
Wavefront OBJ Import/Export is built in to Blender as of v3.3 hence no option to install addon.

**Comment by ZackHaronOriginal** [comment]
I'm getting the same error has anyone found a solution to this?

**Comment by Stefanizam** [comment]
Any solutions for blender 4.0 ?

**Comment by natahnd** [comment]
For blender 3.3 and 4.0, the OBJ Import/Export is now built into the system, so the API calls bpy.ops.export_scene.obj and bpy.ops.import_scene.obj no longer exist. I dug into the blender API changes and found the new functions for OBJ Import/Export and implemented those but I'm not entirely sure it is the correct fix, as some of the arguments from the original functions aren't in the new functions.

However, for someone else to test and verify if they would like, these are the changes I made inside the failing file: 
- jremesh-tools-main\jrt_remesh_op.py

On line 73, I changed the OBJ export command from:
```
# Export original object
bpy.ops.export_scene.obj(filepath=orig,
                            use_selection=True,
                            use_mesh_modifiers=True,
                            use_edges=True,
                            use_smooth_groups=False,
                            use_smooth_groups_bitflags=False,
                            use_normals=True,
                            use_uvs=True)
```

to


```
# Export original object
bpy.ops.wm.obj_export(filepath=orig,
                            check_existing=False,
                            export_selected_objects=True,
                            apply_modifiers=True,
                            export_smooth_groups=False,
                            smooth_group_bitflags=False,
                            export_normals=True,
                            export_uv=True)
```

On line 96, I changed the OBJ Import command from:
```
# Import remeshed object
bpy.ops.import_scene.obj(filepath=output,
                             use_smooth_groups=False)
                             use_image_search=False)
```
to
```
# Import remeshed object
bpy.ops.wm.obj_import(filepath=output,
                             use_split_objects=False)
```

If someone else could verify if these are the correct changes then would be appreciated.
Cheers

**Comment by ddkro** [comment]
> If someone else could verify if these are the correct changes then would be as appreciated as this is the first time using this plugin for me in Blender, so I'm not sure if the results are correct or not, and I haven't installed the older versions to verify. Cheers

4.0, it's not working

**Comment by AutoGrudge** [comment]
@natahnd i ran your fix and got this error

![image](https://github.com/jayanam/jremesh-tools/assets/135097919/6018cdeb-e281-4dfa-b391-557c971b4795)

**Comment by arrafi-musabbir** [comment]
Turns out bpy.ops.import_scene.obj was removed at `bpy>=4` which is the latest blender-api for python, hence the error. In bpy>4 you have to use bpy.ops.wm.obj_import(filepath='')

I just downgraded to `bpy==3.60` and it worked for me:
```
pip install bpy=3.6.0
```

**Comment by jayanam** [comment]
I am in the process of migrating all my addons to Blender >= 4

**Comment by arrafi-musabbir** [comment]
that would be great, thank you!

**Comment by natahnd** [comment]
> @natahnd i ran your fix and got this error
> 
> ![image](https://private-user-images.githubusercontent.com/135097919/294477324-6018cdeb-e281-4dfa-b391-557c971b4795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyOTI0NzQsIm5iZiI6MTcwNTI5MjE3NCwicGF0aCI6Ii8xMzUwOTc5MTkvMjk0NDc3MzI0LTYwMThjZGViLWUyODEtNGRmYS1iMzkxLTU1N2M5NzFiNDc5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwNDE2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTM3ZGY3OGFhMzk5YWUwMjcyOWU4MDE4Y2MwM2EzY2QzMWMxNzQwNzcxNWFlYjIyYTZkMGIxYTdjZGRkZWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.45oaxPcMgr3q54IpULo4Hep4hGmXnJLM1J5D-Brb26k)

The error you're reporting suggests that the changes haven't been applied in your Blender correctly. This likely requires a restart of Blender if you changed the python script whilst it was open. The reason I can tell its not updated is it's saying:

"calling operator bpy.ops.export_scene.obj error" whereas the new function name, if updated correctly is bpy.ops.wm.obj_export. 

That said I would wait for the official update as indicated in the above comments :)
